Repository bmish/check-dependency-version-consistency, pull requests merged in 2021-09, with the labels that each got.

#174 Add help description to CLI `path` argument
  bin/check-dependency-version-consistency.ts
Labels: enhancement

#175 Mention related tool `npm-package-json-lint` in README
  README.md
Labels: documentation

#177 Implement autofixing
  README.md
  bin/check-dependency-version-consistency.ts
  lib/dependency-versions.ts
  package.json
  test/lib/dependency-versions.ts
  yarn.lock
Labels: enhancement

#178 Sort mismatching version output by version number
  lib/output.ts
  test/lib/output.ts
Labels: enhancement

#184 Improve conciseness of error message output
  bin/check-dependency-version-consistency.ts
Labels: bug

#185 Improve output formatting for mismatched versions
  README.md
  lib/output.ts
  package.json
  test/lib/output.ts
Labels: enhancement

#194 Make path argument optional
  README.md
  bin/check-dependency-version-consistency.ts
Labels: enhancement

#192 Describe motivation in README
  README.md
Labels: documentation

#197 Use table to display mismatching version output
  README.md
  bin/check-dependency-version-consistency.ts
  lib/output.ts
  package.json
  test/lib/output.ts
  yarn.lock
Labels: enhancement

#198 Show list of packages containing each dependency version
  README.md
  lib/dependency-versions.ts
  lib/output.ts
  test/lib/dependency-versions.ts
  test/lib/output.ts
Labels: enhancement

#189 Display package versions in descending instead of ascending order
  README.md
  lib/output.ts
  test/lib/output.ts
Labels: enhancement

#205 Improve discoverability of `fix` option
  README.md
  lib/output.ts
  test/lib/output.ts
Labels: enhancement

#206 Bold maximum usage count for each mismatched dependency
  lib/output.ts
  test/lib/output.ts
Labels: enhancement

#214 Add dependency caching to CI
  .github/workflows/ci.yml
Labels: internal
