Repository bmish/check-dependency-version-consistency, pull requests merged in 2022-01, with the labels that each got.

#296 Add `.DS_Store` file to `.gitignore`
  .gitignore
Labels: internal

#298 Add `--ignore-dep-pattern` option
  README.md
  bin/check-dependency-version-consistency.ts
  lib/dependency-versions.ts
  test/lib/dependency-versions.ts
Labels: enhancement

#299 Fix incorrect autofix for nested dependency
  lib/dependency-versions.ts
  package.json
  test/lib/dependency-versions.ts
  yarn.lock
Labels: bug

#300 Switch to jest snapshot testing
  .eslintrc.cjs
  .gitignore
  .npmignore
  jest.config.cjs
  package.json
  test/lib/dependency-versions-test.ts
  test/lib/output-test.ts
  test/lib/output.ts
  test/lib/workspace-test.ts
  tsconfig.json
  yarn.lock
Labels: internal

#303 Add `--ignore-path` and `--ignore-path-pattern` options
  README.md
  bin/check-dependency-version-consistency.ts
  lib/package.ts
  lib/workspace.ts
  test/lib/dependency-versions-test.ts
  test/lib/output-test.ts
  test/lib/package-test.ts
  test/lib/workspace-test.ts
Labels: enhancement

#315 Add more detailed README example section
  README.md
Labels: documentation

#313 Update to `@types/edit-json-file` 1.7.0 and remove `ts-ignore` comment
  lib/dependency-versions.ts
  package.json
  yarn.lock
Labels: internal

#316 Add `eslint-plugin-jest` and update tests
  .eslintrc.cjs
  package.json
  test/lib/dependency-versions-test.ts
  test/lib/package-test.ts
  test/lib/workspace-test.ts
  yarn.lock
Labels: internal

#320 Display which dependencies were fixed when running with `--fix`
  bin/check-dependency-version-consistency.ts
  lib/dependency-versions.ts
  lib/output.ts
  test/lib/dependency-versions-test.ts
  test/lib/output-test.ts
Labels: enhancement

#324 Switch to package.json `files` to only publish necessary files
  .npmignore
  package.json
Labels: bug

#329 Improve completeness of example in README
  README.md
Labels: documentation

#330 Use `latest` version instead of `highest` version
  README.md
  bin/check-dependency-version-consistency.ts
  lib/dependency-versions.ts
  lib/output.ts
  test/lib/dependency-versions-test.ts
Labels: documentation
