Repository bmish/check-dependency-version-consistency, pull requests merged in 2024-12, with the labels that each got.

#700 Update mock-fs to 5.4.1
  package.json
  yarn.lock
Labels: internal

#704 Test under Node 22 and Node 23
  .github/workflows/ci.yml
Labels: internal

#705 Update commander to v11
  package.json
  yarn.lock
Labels: bug

#706 Refresh lockfile
  tsconfig.json
  yarn.lock
Labels: internal

#707 Drop support for Node 16, 19, 21
  .github/workflows/ci.yml
  package.json
Labels: breaking

#708 Update to eslint v9 with flat config
  .eslintignore
  .eslintrc.cjs
  bin/check-dependency-version-consistency.ts
  eslint.config.js
  jest.config.ts
  lib/cdvc.ts
  lib/check.ts
  lib/cli.ts
  lib/dependency-versions.ts
  lib/output.ts
  lib/package.ts
  lib/semver.ts
  lib/workspace.ts
  package.json
  test/fixtures/index.ts
  test/lib/cdvc-test.ts
  test/lib/dependency-versions-test.ts
  test/lib/output-test.ts
  test/lib/package-test.ts
  test/lib/semver-test.ts
  test/lib/workspace-test.ts
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: internal

#709 Update internal dependencies
  package.json
  yarn.lock
Labels: internal

#710 Update globby to v14
  package.json
  yarn.lock
Labels: enhancement

#711 Update commander to v12
  package.json
  yarn.lock
Labels: enhancement

#712 Use ES2023 target for TypeScript
  tsconfig.json
Labels: internal
